### ISSUE TITLE
Cannot read properties of undefined (reading 'displayName')

### ISSUE THREAD

**Issue by Asaf-S** [AttilioCapocchiani/vscode-azure-boards#18]
I'm getting the following error:
```
Cannot read properties of undefined (reading 'displayName')
```

Can you please help me solve it?

**Comment by AttilioCapocchiani** [comment]
Hi @Asaf-S, can I ask you in which occasion this error occurs? Can you post steps to reproduce the error?

**Comment by Asaf-S** [comment]
Yes, thx for answering.

I've installed the extension, and used your excellent 'Getting started' menu to: add the PAT, add the organization name, and adding the query GUID while slecting the org and project.

Then I clicked the refresh/play button to get the results - but got that error message instead...

**Comment by AttilioCapocchiani** [comment]
Hi @Asaf-S . I just release v1.1.1 which will fix this error. Apologies for the extreme delay and I hope you will continue using my extension.
